apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouncing-cats-api-app-chaos
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bouncing-cats-api=ghcr.io/colorful12/container-try-backend
    argocd-image-updater.argoproj.io/bouncing-cats-api.update-strategy: semver
    argocd-image-updater.argoproj.io/bouncing-cats-api.allow-tags: regexp:^chaos-.*
spec:
  project: default
  source:
    repoURL: https://github.com/colorful12/container-try
    targetRevision: nightmare  # 悪夢の破壊テスト用ブランチ
    path: manifests/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: taki  # 既存のtaki namespaceを使用
  syncPolicy:
    automated:
      prune: false   # 破壊状態を保持するため無効化
      selfHeal: false # 破壊状態を観察するため無効化
