apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouncing-cats-api-app-chaos
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bouncing-cats-api=ghcr.io/colorful12/container-try-backend
    argocd-image-updater.argoproj.io/bouncing-cats-api.update-strategy: semver
    argocd-image-updater.argoproj.io/bouncing-cats-api.allow-tags: regexp:^v1\.0\.
spec:
  project: default
  source:
    repoURL: https://github.com/colorful12/container-try
    targetRevision: nightmare
    path: manifests/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: taki
  syncPolicy:
    automated: {} 
