apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/colorful12/container-try-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^v1\.0\.
spec:
  project: default
  source:
    repoURL: https://github.com/colorful12/container-try
    targetRevision: main
    path: manifests/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: taki
  syncPolicy:
    automated: {} 
