apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: taki
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024

    exporters:
      datadog:
        api:
          key: ${DD_API_KEY}
        env: ${DD_ENV}
        service: backend
        version: 1.0.0

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog] 
