apiVersion: apps/v1
kind: Deployment
metadata:
  name: bouncing-cats-ui
  namespace: taki
  labels:
    app: bouncing-cats-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bouncing-cats-ui
  template:
    metadata:
      labels:
        app: bouncing-cats-ui
      annotations:
        ad.datadoghq.com/bouncing-cats-ui.logs: '[{"source": "javascript", "service": "bouncing-cats-ui"}]'
    spec:
      containers:
        - name: bouncing-cats-ui
          image: bouncing-cats-ui
          ports:
            - containerPort: 4200
          livenessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
