apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taki
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        ad.datadoghq.com/backend.logs: '[{"source": "python", "service": "backend"}]'
    spec:
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
