name: Docker Final Kadai Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.4'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          
      - name: Run backend tests
        working-directory: backend
        run: |
          pytest

      - name: Run backend lint (static analysis)
        working-directory: backend
        run: |
          pip install flake8
          flake8 .

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install dependencies
        working-directory: frontend
        run: npm install
        
      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watch=false --browsers=ChromeHeadless
        
      - name: Run frontend lint (static analysis)
        working-directory: frontend
        run: npm run lint
