name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # ghcr.io にpushするために必要
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: |
          # セマンティックバージョニングに準拠
          VERSION="v1.0.${GITHUB_RUN_NUMBER}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${VERSION}"

      - name: Build and push with Compose
        env: 
          REPO_OWNER: ${{ github.repository_owner }}
          DOCKER_DEFAULT_PLATFORM: linux/arm64
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          # 通常のビルド
          docker compose build
          
          # セマンティックバージョニングのタグを付けてpush
          docker tag ghcr.io/colorful12/container-try-frontend:latest ghcr.io/colorful12/container-try-frontend:${VERSION}
          docker tag ghcr.io/colorful12/container-try-backend:latest ghcr.io/colorful12/container-try-backend:${VERSION}
          
          # 両方のタグをpush
          docker push ghcr.io/colorful12/container-try-frontend:latest
          docker push ghcr.io/colorful12/container-try-frontend:${VERSION}
          docker push ghcr.io/colorful12/container-try-backend:latest
          docker push ghcr.io/colorful12/container-try-backend:${VERSION}
          
          echo "Pushed images with tags: latest and ${VERSION}"
