name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # ghcr.io にpushするために必要
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: |
          # セマンティックバージョニングに準拠
          VERSION="v1.0.${GITHUB_RUN_NUMBER}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Generated version: ${VERSION}"

      - name: Build and push optimized
        id: build
        env: 
          REPO_OWNER: ${{ github.repository_owner }}
          DOCKER_DEFAULT_PLATFORM: linux/arm64
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Starting optimized build with GitHub Actions cache..."
          
          # ビルド開始時刻を記録
          BUILD_START=$(date +%s)
          
          # BuildKitで最適化されたバックエンドビルド（キャッシュ使用）
          DOCKER_BUILDKIT=1 docker buildx build \
            --progress=plain \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ghcr.io/colorful12/container-try-backend:latest \
            -t ghcr.io/colorful12/container-try-backend:${VERSION} \
            --push \
            ./backend
          
          if [ $? -ne 0 ]; then
            echo "Backend build failed"
            exit 1
          fi
          
          # BuildKitで最適化されたフロントエンドビルド（キャッシュ使用）
          DOCKER_BUILDKIT=1 docker buildx build \
            --progress=plain \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            -t ghcr.io/colorful12/container-try-frontend:latest \
            -t ghcr.io/colorful12/container-try-frontend:${VERSION} \
            --push \
            ./frontend
          
          if [ $? -ne 0 ]; then
            echo "Frontend build failed"
            exit 1
          fi
          
          # ビルド終了時刻を記録
          BUILD_END=$(date +%s)
          BUILD_DURATION=$((BUILD_END - BUILD_START))
          
          echo "build_duration=${BUILD_DURATION}" >> $GITHUB_OUTPUT
          echo "Optimized build completed in ${BUILD_DURATION} seconds"
          echo "Pushed images with tags: latest and ${VERSION}"

      - name: Build summary
        if: success()
        run: |
          echo "## Optimized Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build completed successfully with optimization" >> $GITHUB_STEP_SUMMARY
          echo "- Backend and Frontend images built and pushed" >> $GITHUB_STEP_SUMMARY
          echo "- Build duration: ${{ steps.build.outputs.build_duration }} seconds" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- Used GitHub Actions cache for faster builds" >> $GITHUB_STEP_SUMMARY
          echo "- BuildKit optimization enabled" >> $GITHUB_STEP_SUMMARY
